### ISSUE TITLE
User registration fails

### ISSUE THREAD

**Issue by vorcigernix** [Developer-DAO/rpc#4]
### Contact Details

vorcigernix@gmail.com

### What is the expected behavior?

When I send a payload to the /api/register  
example 
```
{
    email: "vorcigernix@gmail.com",
    wallet: "0x86782C476d6720a58C6c66e13D421F735Cf9B990",
    password: "test",
}
``` 
user should be registered.

### What is the current behavior?

I get the `Invalid input` reponse

### Reproduction steps

```bash
1. Call the api
2. Get the response
3. Profit
```

### Version

latest

### Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): Latest Nextjs
* Operating System and version (desktop or mobile): ChromeOS
* Link to your project: https://github.com/Developer-DAO/ddrpc-frontend/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crypdoughdoteth** [comment]
I found some stuff wrong with the SMTP configuration, I also wrote a couple of unit tests to accompany the fix. I will merge changes shortly

**Comment by crypdoughdoteth** [comment]
I just pushed some changes that should patch the issue, please let me know if there are any problems running the tests as well. One of the main issues I had actually had to do with my credentials. I needed to generate an app specific password for my gmail. Re-open if anything else pops up
